name: sistem_configure_vt
description: "Progeto para otimizar as configuracoes android."

publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  cloud_firestore: ^4.15.5
  firebase_remote_config: ^4.3.14
  return_success_or_error: ^0.17.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
