name: sistem_configure_vt
description: "Progeto para otimizar as configuracoes android."

publish_to: "none"

version: 2.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  audio_recorder_vt_plugin:
    # path: ../../PLUGIN/audio_recorder_vt_plugin
    git: 
      url: https://github.com/pwlimaverde/audio_recorder_vt_plugin.git
      ref: 0.6.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.3
  cloud_firestore: ^4.17.1
  firebase_remote_config: ^4.3.14
  return_success_or_error: ^0.17.0
  get: ^4.6.6
  workmanager: ^0.5.2
  logger: ^2.2.0
  android_power_manager: ^1.0.0
  get_storage: ^2.1.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  flutter_background_video_recorder: ^0.0.9+1
  intl: ^0.19.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  firebase_auth: ^4.19.3
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icons8-config-1024.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
